name = "hien-le-garden-v4"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "hien_le_garden_crm"
database_id = "bf3ed73c-96de-494c-a3f9-e905f2bf8c48"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "hien-le-garden-finance-receipts"
